services:
  postgres:
    image: postgres:16-alpine
    container_name: mini-paypay-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: paypay-root
      POSTGRES_PASSWORD: tesTing23$
      POSTGRES_DB: paypay_rewards_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U paypay-root -d paypay_rewards_db']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
